import { Book, Testament } from './types';

export const BOOKS: Book[] = [
  // Antiguo Testamento (39 libros)
  { id: 'ot-gen', name: 'Génesis', testament: Testament.OLD, chapters: 50 },
  { id: 'ot-exo', name: 'Éxodo', testament: Testament.OLD, chapters: 40 },
  { id: 'ot-lev', name: 'Levítico', testament: Testament.OLD, chapters: 27 },
  { id: 'ot-num', name: 'Números', testament: Testament.OLD, chapters: 36 },
  { id: 'ot-deu', name: 'Deuteronomio', testament: Testament.OLD, chapters: 34 },
  { id: 'ot-jos', name: 'Josué', testament: Testament.OLD, chapters: 24 },
  { id: 'ot-jue', name: 'Jueces', testament: Testament.OLD, chapters: 21 },
  { id: 'ot-rut', name: 'Rut', testament: Testament.OLD, chapters: 4 },
  { id: 'ot-1sa', name: '1 Samuel', testament: Testament.OLD, chapters: 31 },
  { id: 'ot-2sa', name: '2 Samuel', testament: Testament.OLD, chapters: 24 },
  { id: 'ot-1re', name: '1 Reyes', testament: Testament.OLD, chapters: 22 },
  { id: 'ot-2re', name: '2 Reyes', testament: Testament.OLD, chapters: 25 },
  { id: 'ot-1cr', name: '1 Crónicas', testament: Testament.OLD, chapters: 29 },
  { id: 'ot-2cr', name: '2 Crónicas', testament: Testament.OLD, chapters: 36 },
  { id: 'ot-esd', name: 'Esdras', testament: Testament.OLD, chapters: 10 },
  { id: 'ot-neh', name: 'Nehemías', testament: Testament.OLD, chapters: 13 },
  { id: 'ot-est', name: 'Ester', testament: Testament.OLD, chapters: 10 },
  { id: 'ot-job', name: 'Job', testament: Testament.OLD, chapters: 42 },
  { id: 'ot-sal', name: 'Salmos', testament: Testament.OLD, chapters: 150 },
  { id: 'ot-pro', name: 'Proverbios', testament: Testament.OLD, chapters: 31 },
  { id: 'ot-ecl', name: 'Eclesiastés', testament: Testament.OLD, chapters: 12 },
  { id: 'ot-can', name: 'Cantares', testament: Testament.OLD, chapters: 8 },
  { id: 'ot-isa', name: 'Isaías', testament: Testament.OLD, chapters: 66 },
  { id: 'ot-jer', name: 'Jeremías', testament: Testament.OLD, chapters: 52 },
  { id: 'ot-lam', name: 'Lamentaciones', testament: Testament.OLD, chapters: 5 },
  { id: 'ot-eze', name: 'Ezequiel', testament: Testament.OLD, chapters: 48 },
  { id: 'ot-dan', name: 'Daniel', testament: Testament.OLD, chapters: 12 },
  { id: 'ot-ose', name: 'Oseas', testament: Testament.OLD, chapters: 14 },
  { id: 'ot-joe', name: 'Joel', testament: Testament.OLD, chapters: 3 },
  { id: 'ot-amo', name: 'Amós', testament: Testament.OLD, chapters: 9 },
  { id: 'ot-abd', name: 'Abdías', testament: Testament.OLD, chapters: 1 },
  { id: 'ot-jon', name: 'Jonás', testament: Testament.OLD, chapters: 4 },
  { id: 'ot-miq', name: 'Miqueas', testament: Testament.OLD, chapters: 7 },
  { id: 'ot-nah', name: 'Nahúm', testament: Testament.OLD, chapters: 3 },
  { id: 'ot-hab', name: 'Habacuc', testament: Testament.OLD, chapters: 3 },
  { id: 'ot-sof', name: 'Sofonías', testament: Testament.OLD, chapters: 3 },
  { id: 'ot-hag', name: 'Hageo', testament: Testament.OLD, chapters: 2 },
  { id: 'ot-zac', name: 'Zacarías', testament: Testament.OLD, chapters: 14 },
  { id: 'ot-mal', name: 'Malaquías', testament: Testament.OLD, chapters: 4 },

  // Nuevo Testamento (27 libros)
  { id: 'nt-mat', name: 'Mateo', testament: Testament.NEW, chapters: 28 },
  { id: 'nt-mar', name: 'Marcos', testament: Testament.NEW, chapters: 16 },
  { id: 'nt-luc', name: 'Lucas', testament: Testament.NEW, chapters: 24 },
  { id: 'nt-jua', name: 'Juan', testament: Testament.NEW, chapters: 21 },
  { id: 'nt-hch', name: 'Hechos', testament: Testament.NEW, chapters: 28 },
  { id: 'nt-rom', name: 'Romanos', testament: Testament.NEW, chapters: 16 },
  { id: 'nt-1co', name: '1 Corintios', testament: Testament.NEW, chapters: 16 },
  { id: 'nt-2co', name: '2 Corintios', testament: Testament.NEW, chapters: 13 },
  { id: 'nt-gal', name: 'Gálatas', testament: Testament.NEW, chapters: 6 },
  { id: 'nt-efe', name: 'Efesios', testament: Testament.NEW, chapters: 6 },
  { id: 'nt-fil', name: 'Filipenses', testament: Testament.NEW, chapters: 4 },
  { id: 'nt-col', name: 'Colosenses', testament: Testament.NEW, chapters: 4 },
  { id: 'nt-1te', name: '1 Tesalonicenses', testament: Testament.NEW, chapters: 5 },
  { id: 'nt-2te', name: '2 Tesalonicenses', testament: Testament.NEW, chapters: 3 },
  { id: 'nt-1ti', name: '1 Timoteo', testament: Testament.NEW, chapters: 6 },
  { id: 'nt-2ti', name: '2 Timoteo', testament: Testament.NEW, chapters: 4 },
  { id: 'nt-tit', name: 'Tito', testament: Testament.NEW, chapters: 3 },
  { id: 'nt-flm', name: 'Filemón', testament: Testament.NEW, chapters: 1 },
  { id: 'nt-heb', name: 'Hebreos', testament: Testament.NEW, chapters: 13 },
  { id: 'nt-san', name: 'Santiago', testament: Testament.NEW, chapters: 5 },
  { id: 'nt-1pe', name: '1 Pedro', testament: Testament.NEW, chapters: 5 },
  { id: 'nt-2pe', name: '2 Pedro', testament: Testament.NEW, chapters: 3 },
  { id: 'nt-1ju', name: '1 Juan', testament: Testament.NEW, chapters: 5 },
  { id: 'nt-2ju', name: '2 Juan', testament: Testament.NEW, chapters: 1 },
  { id: 'nt-3ju', name: '3 Juan', testament: Testament.NEW, chapters: 1 },
  { id: 'nt-jud', name: 'Judas', testament: Testament.NEW, chapters: 1 },
  { id: 'nt-apo', name: 'Apocalipsis', testament: Testament.NEW, chapters: 22 },
];